### ISSUE TITLE
Issue importing collection with Runscope format

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/runscope-to-postman#15]
**Describe the bug**
Error while a file with Runscope format in Postman is imported.

**To Reproduce**
1. Click on Import.
2. Import a collection with Runscope format.
3. Error message

<img width="345" alt="Screenshot 2020-07-08 at 4 15 51 PM" src="https://user-images.githubusercontent.com/47771757/86909823-51068d00-c136-11ea-9b7a-c60ea6f212a6.png">

**Expected behavior**
Be able to import collection without any issue.

**Screenshots**

<img width="776" alt="Screenshot 2020-07-08 at 4 13 54 PM" src="https://user-images.githubusercontent.com/47771757/86909707-20265800-c136-11ea-9f32-740d6e6fab6b.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v.7.27.1
 - OS: Mac

**Additional context**
_Filed by Prouct Support_

**Comment by Ranchman42** [comment]
I am having the same issue. I would like to be able to import runscope tests into postman.

Thanks!

**Comment by colbyjayallen** [comment]
This issue is active for my team as well, we are doing a migration of a lot of tests over from Runscope to Postman. @Raj-postman it looks like this ticket has been opened for more than two months, has this issue been triaged?

* App Type: Native App
* Postman Version: 7.32.0
* OS: Windows

**Comment by umeshp7** [comment]
This issue is fixed in v8 of the Postman app.
